### ISSUE TITLE
Rollback to before Yoast injection

### ISSUE THREAD

**Issue by Chrillaz** [NoorDigitalAgency/wp_structured_data#1]

**Comment by Chrillaz** [comment]
Jag har tagit bort steget som invokar Yoast. Så den bör funka som innan nu.
Intallerad och kan testas på tuttobalutto.noor-dev.se @shayansalehi

**Comment by shayansalehi** [comment]
Vilken undersida har du faq på? :)

**Comment by Chrillaz** [comment]
sorry
https://tuttobalutto.noor-dev.se/kronikor/ @shayansalehi

**Comment by Chrillaz** [comment]
testa gärna en krönika också så att selectorn för underkategorier också är fortsatt intakt. @shayansalehi

**Comment by shayansalehi** [comment]
Funkar fint, har lämnat den kvar på tutto. Så du vill nog ta bort det innan vi går live :)

**Comment by Chrillaz** [comment]
@shayansalehi Perfekt. Tack!
Jag släpperr ny release så där det inte funkar får vi uppdatera.

**Comment by Chrillaz** [comment]
v1.3.3 release

**Comment by shayansalehi** [comment]
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fresmedbarn.nu%2Fbasta-babyvakten-2020%2F

Seems to still be integrated with yoast.

**Comment by shayansalehi** [comment]
False alarm, above was another "tool".
