### ISSUE TITLE
Move from verktyg and to the general sidebar list

### ISSUE THREAD

**Issue by shayansalehi** [NoorDigitalAgency/wp_structured_data#4]
![image](https://user-images.githubusercontent.com/26716958/111527036-b435ce00-875f-11eb-9664-1748c247b151.png)

**Comment by Chrillaz** [comment]
Page is now in admin menu top level. Look for it at the bottom of the menu.
Capability is 'read' which is lowest priority/capabillity possible.

Test can be don on kaffeinformation.
I've created a user to test capabillity/roles to.
N: testuser  P: test

@shayansalehi

**Comment by shayansalehi** [comment]
Looks fine, but make sure this is not related to https://github.com/NoorDigitalAgency/wp_structured_data/issues/6

**Comment by shayansalehi** [comment]
Approved

**Comment by Chrillaz** [comment]
Release 1.4.0
