### ISSUE TITLE
Plugin compat with PHP 5.2> and multisite

### ISSUE THREAD

**Issue by Chrillaz** [NoorDigitalAgency/wp_structured_data#5]
Tested on narvaderma which runs on php 5.3 and is multisite.
Faq passed test on google testing tool for structured data.

https://search.google.com/structured-data/testing-tool/u/0/?hl=sv#url=https%3A%2F%2Fnarvaderma.se%2Fskonhetsbehandlingar%2Fbotox%2F

Double check on kaffeinformation. and narvaderma before new release @shayansalehi

**Comment by shayansalehi** [comment]
Is this related to this problem? https://github.com/NoorDigitalAgency/wp_structured_data/issues/6

**Comment by Chrillaz** [comment]
No this is not related. @shayansalehi

**Comment by shayansalehi** [comment]
Approved

**Comment by Chrillaz** [comment]
Release 1.4.0
