### ISSUE TITLE
Missing field 'mainEntity'

### ISSUE THREAD

**Issue by shayansalehi** [NoorDigitalAgency/wp_structured_data#6]
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.kaffeinformation.se%2Fbryggmetoder%2Fkaffekokare%2Fperkulator%2F

https://www.kaffeinformation.se/bryggmetoder/kaffekokare/perkulator/

It is the latest version, Version 1.3.3 

https://europe-enterprise.taskworld.com/noor/#/home?show=/task/56744

**Comment by Chrillaz** [comment]
<img width="825" alt="Screenshot 2021-03-22 at 07 15 56" src="https://user-images.githubusercontent.com/35850193/111947954-a32de980-8ade-11eb-9792-65ad9f674cc1.png">

Issue is on yoast structured data.

Inspecting the source we provide our structured data with mainEntity

![image](https://user-images.githubusercontent.com/35850193/111948048-d2445b00-8ade-11eb-83c9-85502dd5443d.png)

Maybe cloudflare? I had to refresh to get the structured data to take affect.
@shayansalehi

**Comment by shayansalehi** [comment]
@Chrillaz I have empty the cache through Cloudflare, it was not that.  I have put it in developer mode.

I thought Version 1.3.3 fixed the problem and that we do not insert it through Yoast anymore?

**Comment by Chrillaz** [comment]
We're not inserting on Yoast.
The images above displays our own script tag with structured data json.
And the error points to yoast script structured data.

I'll see if that page uses the yoast in some way. I'll dig deeper on this.
@shayansalehi

**Comment by shayansalehi** [comment]
@Chrillaz Pretty much all our pages use Yoast, but on that page, we do not use FAQ structured data through yoast.

![image](https://user-images.githubusercontent.com/26716958/111962975-4be64400-8af3-11eb-8ecd-d3323cdcec97.png)

**Comment by Chrillaz** [comment]
https://search.google.com/structured-data/testing-tool/u/0/?hl=sv#url=https%3A%2F%2Fwww.kaffeinformation.se%2Fbryggmetoder%2Fkaffekokare%2Fperkulator%2F

Ok. i changed the yoast settings for the page. and it seems to be working now.
Switched to web-page, saved and then back to (default for page Web-page) and saved.

![image](https://user-images.githubusercontent.com/35850193/111963031-5bfe2380-8af3-11eb-816f-d3ddb876119c.png)

@shayansalehi

**Comment by Chrillaz** [comment]
Yes i know. But the issue was somehow related to the yoast settings rather than the plugin structured_data.

Could be that the data got stored to Yoast previously and that's why "re save/setting" fixed the table on Yoast.
@shayansalehi

**Comment by Chrillaz** [comment]
Though im unsertain when all other pages did not require to resave the yoast settings.

If it was prev saved on the Yoast table it whould have been the same for all pages. is my assumption..

Do you know any other site that used the version where we injected to Yoast before removing it? Just so i can debugg on another case to.

@shayansalehi

**Comment by shayansalehi** [comment]
Approved

**Comment by Chrillaz** [comment]
Release 1.4.0

**Comment by alirezayosefian** [comment]
Hello, good time
I'm wrong with the FAQ schema,"
in google schema checker show this error : "Missing field "mainEntity""
it shows @type":["WebPage","FAQPage"].
My problem is exactly like yours. Thank you for viewing the [[dowry carpet buying](https://hyperfarsh.com/%d8%b1%d8%a7%d9%87%d9%86%d9%85%d8%a7%db%8c-%da%a9%d8%a7%d9%85%d9%84-%d8%ae%d8%b1%db%8c%d8%af-%d9%81%d8%b1%d8%b4-%d8%ac%d9%87%db%8c%d8%b2%db%8c%d9%87/)] post and guiding us.
thank you
