### ISSUE TITLE
Role permission for saving to options.php

### ISSUE THREAD

**Issue by Chrillaz** [NoorDigitalAgency/wp_structured_data#7]
Role with read access cannot save options page

**Comment by Chrillaz** [comment]
Kanse vi skall ta ner senaste versionen från master och installera direkt på kundsidan för att testa här @shayansalehi 
Har uppdaterat kaffe information iaf med denna version för testing.

**Comment by shayansalehi** [comment]
Kunden är watercircles och där har vi inte access till att installera eller uppdatera plugins.

Hur tetar vi på kaffeinformation, kan vi skapa en user med lägre behörighet och testa?

**Comment by Chrillaz** [comment]
Plugin uppdaterat på kaffeinformation. @shayansalehi

**Comment by shayansalehi** [comment]
ok, har du testat det själv med testuser först? (lösenordet funkar inte för mig)

**Comment by shayansalehi** [comment]
funkar fint!

**Comment by shayansalehi** [comment]
Redo att deployas

**Comment by Chrillaz** [comment]
Release 1.4.1
